### ISSUE TITLE
Integration miheater not found

### ISSUE THREAD

**Issue by JamesMcCarthy79** [fineemb/Smartmi-smart-heater#3]
Platform error climate.miheater - Integration 'miheater' not found.

HA Version - 0.109.6

Added Component through HACS Version - 1.21

Config
```
  - platform: miheater
    host: !secret heater_ip
    token: !secret heater_token
    name: Upstairs Heater
    hvac_mode: true
    target_sensor: sensor.upstairs_temperature
```

**Comment by sumoto** [comment]
put this integration to folder \custom_components\

**Comment by JamesMcCarthy79** [comment]
you may need to update your component instructions to reflect this.

**Comment by Double-Dude** [comment]
Hi @JamesMcCarthy79 , how did you fix the issue? I've added through HACS as well, it automatically added the integration into config/custom_components/ .
