### ISSUE TITLE
python-miio dependancy

### ISSUE THREAD

**Issue by JamesMcCarthy79** [fineemb/Smartmi-smart-heater#4]
Hi there I thought I would let you know that any custom_component using the python-miio dependancy since 0.109.0 needs to use `"python-miio>=0.5.0.1"` otherwise it causes issues with any of the entities using the core integration (for me vacuum). I updated the manifest.json to `"python-miio>=0.5.0.1"` and this resolved the issue for me.

**Comment by fineemb** [comment]
v1.22 update
